apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-silver-games
spec:
  schedule: "30 12 * * 3"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-silver-games
            image: update_silver_etl:latest
            imagePullPolicy: Never
            command: ["python3"]
            args: ["silver_data_loader.py"]
            env:
            - name: MONGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGO_DB_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: mongo-creds
                 key: password
            - name: MONGO_DB_HOST
              value: mongo-nodeport-svc
            - name: MONGO_DB_PORT
              value: "27017"
          restartPolicy: OnFailure

