FROM python:3.10-slim as deps

# Set the current directory inside the container to /app
WORKDIR /app

# Install dependencies
COPY src/update_new_games/requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Set the user to non-root
USER nobody

FROM deps

# Copy the content of the local src directory to the working directory
COPY src/test-tqdm/test-tqdm.py /app